// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagementWeb.Infrastructure.Data;

#nullable disable

namespace WarehouseManagementWeb.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321034028_AddTableBalances")]
    partial class AddTableBalances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.BalanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("measure_unit_id")
                        .HasComment("Id единицы измерения.");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasComment("Количество ресурса.");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id")
                        .HasComment("Id ресурса.");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("ResourceId", "MeasureUnitId")
                        .IsUnique();

                    b.ToTable("balances", "warehouse", t =>
                        {
                            t.HasComment("Таблица остатков ресурсов на складе.");

                            t.HasCheckConstraint("ck_balances_quantity_not_negative", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address")
                        .HasComment("Адрес клиента.");

                    b.Property<string>("ClientStatusEnum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status_enum")
                        .HasComment("Статус клиента в значении перечисления.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование клиента.");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("clients", "directory", t =>
                        {
                            t.HasComment("Таблица клиентов.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.DocumentReceiptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id")
                        .HasComment("Id клиента документа поступления.");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата документа поступления.");

                    b.Property<string>("NumberCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number_code")
                        .HasComment("Номер документа поступления.");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumberCode")
                        .IsUnique();

                    b.ToTable("document_receipts", "warehouse", t =>
                        {
                            t.HasComment("Таблица документов поступлений.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.DocumentShipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id")
                        .HasComment("Id клиента документа отгрузки.");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата документа отгрузки.");

                    b.Property<string>("DocumentShipmentStatusEnum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status_enum")
                        .HasComment("Статус документа отгрузки в значении перечисления.");

                    b.Property<string>("NumberCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number_code")
                        .HasComment("Номер документа отгрузки.");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumberCode")
                        .IsUnique();

                    b.ToTable("document_shipments", "warehouse", t =>
                        {
                            t.HasComment("Таблица документов отгрузок.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.MeasureUnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasureUnitStatusEnum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status_enum")
                        .HasComment("Статус единицы измерения в значении перечисления.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Наименование единицы измерения.");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("measure_units", "directory", t =>
                        {
                            t.HasComment("Таблица единиц измерений.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ResourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResourceStatusEnum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status_enum")
                        .HasComment("Статус ресурса в значении перечисления.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Наименование ресурса.");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("resources", "directory", t =>
                        {
                            t.HasComment("Таблица ресурсов.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ResourceReceiptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("document_receipt_id")
                        .HasComment("Id документа поступления.");

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("measure_unit_id")
                        .HasComment("Id единицы измерения.");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasComment("Количество ресурса поступления.");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id")
                        .HasComment("Id ресурса.");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("DocumentReceiptId", "ResourceId", "MeasureUnitId")
                        .IsUnique();

                    b.ToTable("resource_receipts", "warehouse", t =>
                        {
                            t.HasComment("Таблица ресурсов поступлений.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ResourceShipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("PK.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentShipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_shipment_id")
                        .HasComment("Id документа отгрузки.");

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("measure_unit_id")
                        .HasComment("Id единицы измерения.");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasComment("Количество ресурса отгрузки.");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id")
                        .HasComment("Id ресурса.");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("DocumentShipmentId", "ResourceId", "MeasureUnitId")
                        .IsUnique();

                    b.ToTable("resource_shipments", "warehouse", t =>
                        {
                            t.HasComment("Таблица ресурсов отгрузок.");
                        });
                });

            modelBuilder.Entity("WarehouseManagementWeb.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegisteredIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.BalanceEntity", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Domain.Entities.MeasureUnitEntity", "MeasureUnitEntity")
                        .WithMany("BalanceEntities")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagementWeb.Domain.Entities.ResourceEntity", "ResourceEntity")
                        .WithMany("BalanceEntities")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MeasureUnitEntity");

                    b.Navigation("ResourceEntity");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.DocumentReceiptEntity", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Domain.Entities.ClientEntity", "ClientEntity")
                        .WithMany("DocumentReceiptEntities")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientEntity");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.DocumentShipmentEntity", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Domain.Entities.ClientEntity", "ClientEntity")
                        .WithMany("DocumentShipmentEntities")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClientEntity");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ResourceReceiptEntity", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Domain.Entities.DocumentReceiptEntity", "DocumentReceiptEntity")
                        .WithMany("ResourceReceiptEntities")
                        .HasForeignKey("DocumentReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagementWeb.Domain.Entities.MeasureUnitEntity", "MeasureUnitEntity")
                        .WithMany("ResourceReceiptEntities")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagementWeb.Domain.Entities.ResourceEntity", "ResourceEntity")
                        .WithMany("ResourceReceiptEntities")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DocumentReceiptEntity");

                    b.Navigation("MeasureUnitEntity");

                    b.Navigation("ResourceEntity");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ResourceShipmentEntity", b =>
                {
                    b.HasOne("WarehouseManagementWeb.Domain.Entities.DocumentShipmentEntity", "DocumentShipmentEntity")
                        .WithMany("ResourceShipmentEntities")
                        .HasForeignKey("DocumentShipmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagementWeb.Domain.Entities.MeasureUnitEntity", "MeasureUnitEntity")
                        .WithMany("ResourceShipmentEntities")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagementWeb.Domain.Entities.ResourceEntity", "ResourceEntity")
                        .WithMany("ResourceShipmentEntities")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DocumentShipmentEntity");

                    b.Navigation("MeasureUnitEntity");

                    b.Navigation("ResourceEntity");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ClientEntity", b =>
                {
                    b.Navigation("DocumentReceiptEntities");

                    b.Navigation("DocumentShipmentEntities");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.DocumentReceiptEntity", b =>
                {
                    b.Navigation("ResourceReceiptEntities");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.DocumentShipmentEntity", b =>
                {
                    b.Navigation("ResourceShipmentEntities");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.MeasureUnitEntity", b =>
                {
                    b.Navigation("BalanceEntities");

                    b.Navigation("ResourceReceiptEntities");

                    b.Navigation("ResourceShipmentEntities");
                });

            modelBuilder.Entity("WarehouseManagementWeb.Domain.Entities.ResourceEntity", b =>
                {
                    b.Navigation("BalanceEntities");

                    b.Navigation("ResourceReceiptEntities");

                    b.Navigation("ResourceShipmentEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
